controller_list:
  - name: fake_kr10r1100_arm_controller
    joints:
      - q1
      - q2
      - q3
      - q4
      - q5
      - q6
initial:  # Define initial robot poses.
  - group: kr10r1100_arm
    pose: home