# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  q1:
    has_velocity_limits: true
    max_velocity: 5.23598775598
    has_acceleration_limits: false
    max_acceleration: 0
  q2:
    has_velocity_limits: true
    max_velocity: 3.92699081699
    has_acceleration_limits: false
    max_acceleration: 0
  q3:
    has_velocity_limits: true
    max_velocity: 3.92699081699
    has_acceleration_limits: false
    max_acceleration: 0
  q4:
    has_velocity_limits: true
    max_velocity: 6.6497044501
    has_acceleration_limits: false
    max_acceleration: 0
  q5:
    has_velocity_limits: true
    max_velocity: 5.4279739737
    has_acceleration_limits: false
    max_acceleration: 0
  q6:
    has_velocity_limits: true
    max_velocity: 8.58701991981
    has_acceleration_limits: false
    max_acceleration: 0