# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: kr10r1100_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - q1
    - q2
    - q3
    - q4
    - q5
    - q6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - q1
    - q2
    - q3
    - q4
    - q5
    - q6
  gains:
    q1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    q2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    q3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    q4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    q5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    q6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1